version: "2.1"

services:
  postgres:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=homemote
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "user", "-d", "homemote"]
      interval: 5s
      timeout: 10s
      retries: 3
