version: "2.1"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      - network.bind_host=0.0.0.0
      - cluster.name=homemote
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl" ,"--fail", "localhost:9200"]
      interval: 3s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=homemote
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "user", "-d", "homemote"]
      interval: 5s
      timeout: 10s
      retries: 3
